In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint

In [2]:
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [3]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [4]:
with tf.variable_scope('one_cell') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)
    
    x_data = np.array([[h]], dtype=np.float32)
    pp.pprint(x_data)
    outputs, _state = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    #hidden size 만큼 출력
    pp.pprint(outputs.eval())

2 2
array([[[1., 0., 0., 0.]]], dtype=float32)
array([[[ 0.6925702 , -0.02850666]]], dtype=float32)


In [6]:
with tf.variable_scope('two_sequances') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[ 0.28753763, -0.48789468],
        [ 0.45348004, -0.47437233],
        [ 0.58086133,  0.3181398 ],
        [ 0.25222898,  0.05978265],
        [-0.56033087,  0.5173472 ]]], dtype=float32)


In [7]:
with tf.variable_scope('3_batches') as scope:
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l], 
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[-0.12428677,  0.09898727],
        [-0.07614879,  0.04636622],
        [ 0.04868628,  0.12313522],
        [ 0.13089333,  0.17737962],
        [ 0.16754557,  0.28112426]],

       [[ 0.02874899, -0.07731018],
        [ 0.08927929,  0.01233427],
        [ 0.17031981,  0.11014006],
        [ 0.22527236,  0.1690361 ],
        [ 0.2642502 ,  0.2016426 ]],

       [[ 0.09499863,  0.10485959],
        [ 0.16748542,  0.16645683],
        [ 0.18493325,  0.1599472 ],
        [ 0.1549708 ,  0.06525774],
        [ 0.18207154,  0.12977664]]], dtype=float32)
