In [1]:
import tensorflow as tf
import numpy as np

In [3]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [48]:
# np.min(), np.max() test
a = np.array([[1., 2.], [3., -4.]])
b = np.array([[2., 3.], [5., 2.]])
min = np.min(a, 0) #각 행에서 가장 작은 값들만 추출
max = np.max(b, 0)
print(min, max)
print(a - min)
print(min-max)

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

xy = MinMaxScaler(xy)
print(xy)

[ 1. -4.] [ 5.  3.]
[[ 0.  6.]
 [ 2.  0.]]
[-4. -7.]
[[ 0.9999999   0.9999999   0.          0.9999999   0.9999999 ]
 [ 0.70548484  0.70439545  0.9999999   0.71881775  0.83755783]
 [ 0.54412544  0.50274819  0.5760869   0.60646794  0.66063303]
 [ 0.33890349  0.3136802   0.10869564  0.4598913   0.43800914]
 [ 0.51435995  0.42582385  0.3043478   0.585048    0.42624397]
 [ 0.49556174  0.42582385  0.31521736  0.48131129  0.49276132]
 [ 0.11436063  0.          0.20652172  0.22007774  0.18597236]
 [ 0.          0.07747099  0.53260864  0.          0.        ]]


In [49]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  0.173372 
Prediction:
 [[ 1.2592473 ]
 [ 0.88056314]
 [ 0.84095812]
 [ 0.77829486]
 [ 0.87962949]
 [ 0.9836269 ]
 [ 0.67813432]
 [ 0.69345182]]
1 Cost:  0.173364 
Prediction:
 [[ 1.25923204]
 [ 0.8805477 ]
 [ 0.84094501]
 [ 0.77828425]
 [ 0.87961733]
 [ 0.9836151 ]
 [ 0.6781255 ]
 [ 0.693443  ]]
2 Cost:  0.173356 
Prediction:
 [[ 1.25921679]
 [ 0.88053244]
 [ 0.84093189]
 [ 0.77827364]
 [ 0.87960517]
 [ 0.98360324]
 [ 0.67811668]
 [ 0.69343418]]
3 Cost:  0.173348 
Prediction:
 [[ 1.25920153]
 [ 0.88051701]
 [ 0.84091878]
 [ 0.77826303]
 [ 0.87959307]
 [ 0.98359144]
 [ 0.67810786]
 [ 0.6934253 ]]
4 Cost:  0.17334 
Prediction:
 [[ 1.25918627]
 [ 0.88050163]
 [ 0.84090567]
 [ 0.77825242]
 [ 0.87958091]
 [ 0.98357964]
 [ 0.67809904]
 [ 0.69341648]]
5 Cost:  0.173332 
Prediction:
 [[ 1.25917101]
 [ 0.88048631]
 [ 0.84089255]
 [ 0.77824187]
 [ 0.87956882]
 [ 0.98356777]
 [ 0.67809027]
 [ 0.69340765]]
6 Cost:  0.173324 
Prediction:
 [[ 1.25915575]
 [ 0.88047093]
 [ 0.84087944]
 [ 0.7