In [1]:
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [4]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3])) #tf.random_normal([입력값수, 출력값수])
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#Correct prediction Test model
prediction =tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [7]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], 
                                      feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 8.65529 [[ 0.63253433  1.14261734  1.54431093]
 [-1.54656148  0.37124208  0.02253924]
 [-0.62691289 -0.70804447  1.2368114 ]]
1 5.65471 [[ 0.6575278   1.1706332   1.49130166]
 [-1.38407481  0.52447289 -0.2931782 ]
 [-0.46441981 -0.53296727  0.89924115]]
2 4.60818 [[ 0.68251628  1.17422998  1.46271646]
 [-1.22159958  0.56953263 -0.50071311]
 [-0.30193487 -0.44420603  0.647995  ]]
3 3.70268 [[ 0.7074914   1.13535607  1.47661531]
 [-1.05915511  0.38773519 -0.48136008]
 [-0.13948886 -0.57956731  0.62091029]]
4 2.85856 [[ 0.73239839  1.12049723  1.46656716]
 [-0.89687997  0.33273602 -0.58863604]
 [ 0.02277656 -0.5860306   0.46510819]]
5 2.03828 [[ 0.75699174  1.08974731  1.47272372]
 [-0.73546576  0.19263774 -0.60995191]
 [ 0.18379867 -0.67915678  0.39721227]]
6 1.39847 [[ 0.7796886   1.07252038  1.46725368]
 [-0.58102775  0.1237803  -0.6955325 ]
 [ 0.3362093  -0.70114481  0.26678967]]
7 1.29779 [[ 0.78884351  1.05278254  1.47783673]
 [-0.49117002  0.04165494 -0.70326483]
 [ 0.4159677  -0

110 0.657423 [[ 0.26484954  0.51779664  2.53681636]
 [-0.27115414 -0.47266191 -0.40896374]
 [ 0.35260853  0.07407871 -0.52483273]]
111 0.655971 [[ 0.26073909  0.5152095   2.54351401]
 [-0.27078786 -0.47239023 -0.40960169]
 [ 0.35393146  0.07507887 -0.52715582]]
112 0.654536 [[ 0.25663856  0.51265383  2.55017018]
 [-0.27042711 -0.47210622 -0.41024643]
 [ 0.35525542  0.07605308 -0.52945399]]
113 0.653118 [[ 0.25254783  0.51012909  2.55678558]
 [-0.27007166 -0.47181061 -0.41089746]
 [ 0.35658032  0.07700212 -0.53172791]]
114 0.651716 [[ 0.24846679  0.507635    2.56336069]
 [-0.26972133 -0.47150403 -0.41155434]
 [ 0.35790598  0.07792684 -0.53397828]]
115 0.650331 [[ 0.24439533  0.50517106  2.56989598]
 [-0.26937595 -0.47118711 -0.41221663]
 [ 0.35923228  0.07882801 -0.53620577]]
116 0.648962 [[ 0.24033333  0.50273693  2.57639217]
 [-0.26903534 -0.47086045 -0.41288391]
 [ 0.36055911  0.07970639 -0.53841096]]
117 0.647609 [[ 0.23628071  0.50033224  2.5828495 ]
 [-0.26869935 -0.47052452 -0.41