In [1]:
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [3]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3])) #tf.random_normal([입력값수, 출력값수])
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [8]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(1501):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], 
                                      feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    # close test    
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_data}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_data, Y: y_data}))
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 4.83326 [[-0.35340074 -0.62626553 -2.13455153]
 [-0.26838791  0.61753303 -0.10394311]
 [-0.20206146  0.70266187 -0.92083782]]
1 2.8416 [[-0.33046788 -0.68610066 -2.09764934]
 [-0.11041343  0.36081699 -0.00520156]
 [-0.04234258  0.4561125  -0.83400732]]
2 1.61675 [[-0.31479931 -0.73766416 -2.06175447]
 [ 0.02812395  0.12587889  0.09119914]
 [ 0.09915242  0.22922079 -0.74861062]]
3 1.36035 [[-0.3410269  -0.74585801 -2.02733302]
 [-0.01921152  0.08104488  0.18336864]
 [ 0.0493588   0.19684184 -0.66643804]]
4 1.16579 [[-0.36268356 -0.75580412 -1.99573028]
 [-0.0472123   0.02630833  0.26610595]
 [ 0.01810737  0.15354252 -0.5918873 ]]
5 1.07943 [[ -3.84581894e-01  -7.59864867e-01  -1.96977127e+00]
 [ -8.11281651e-02   1.39447115e-03   3.24935704e-01]
 [ -2.04546005e-02   1.38151303e-01  -5.37934124e-01]]
6 1.06501 [[-0.39843374 -0.76349533 -1.95228899]
 [-0.07717323 -0.02047864  0.3428539 ]
 [-0.02294696  0.12304603 -0.52033651]]
7 1.05712 [[-0.41302255 -0.76205885 -1.93913662]
 [-0.078211

90 0.739792 [[-1.17250538 -0.79110289 -1.15060949]
 [ 0.15823087 -0.02476502  0.11173645]
 [ 0.04313241  0.16023582 -0.62360537]]
91 0.737898 [[-1.17915022 -0.79127312 -1.14379442]
 [ 0.15942024 -0.02412044  0.10990249]
 [ 0.04458161  0.15989448 -0.62471324]]
92 0.736028 [[-1.18575847 -0.79143667 -1.13702261]
 [ 0.16059138 -0.02347744  0.10808835]
 [ 0.0460346   0.1595522  -0.62582397]]
93 0.734179 [[-1.1923306  -0.79159361 -1.13029349]
 [ 0.16174446 -0.02283608  0.10629391]
 [ 0.04749113  0.15920919 -0.62693745]]
94 0.732351 [[-1.1988672  -0.79174393 -1.12360656]
 [ 0.16287996 -0.0221966   0.10451894]
 [ 0.04895118  0.15886551 -0.62805378]]
95 0.730545 [[-1.20536876 -0.79188764 -1.11696124]
 [ 0.16399807 -0.02155907  0.10276331]
 [ 0.05041454  0.15852137 -0.62917298]]
96 0.728759 [[-1.21183574 -0.79202479 -1.11035705]
 [ 0.16509917 -0.02092372  0.10102684]
 [ 0.05188115  0.15817678 -0.63029504]]
97 0.726994 [[-1.21826863 -0.79215539 -1.1037935 ]
 [ 0.16618353 -0.02029057  0.09930936]


204 0.60675 [[-1.77507758 -0.77653766 -0.56260175]
 [ 0.22448659  0.02902494 -0.0083088 ]
 [ 0.21497788  0.12546277 -0.76067781]]
205 0.606 [[-1.77945161 -0.77619064 -0.55857468]
 [ 0.224718    0.02933902 -0.0088543 ]
 [ 0.21645878  0.1251993  -0.76189524]]
206 0.605254 [[-1.78381515 -0.77584106 -0.55456072]
 [ 0.22494625  0.02965115 -0.00939466]
 [ 0.21793851  0.12493622 -0.76311189]]
207 0.604511 [[-1.78816819 -0.77548897 -0.55055976]
 [ 0.22517128  0.02996138 -0.00992993]
 [ 0.21941699  0.12467355 -0.7643277 ]]
208 0.603773 [[-1.79251087 -0.77513444 -0.54657167]
 [ 0.22539322  0.0302697  -0.01046019]
 [ 0.22089423  0.12441124 -0.76554263]]
209 0.603038 [[-1.79684317 -0.77477741 -0.54259634]
 [ 0.22561203  0.0305762  -0.0109855 ]
 [ 0.22237021  0.12414938 -0.76675671]]
210 0.602308 [[-1.80116522 -0.774418   -0.53863364]
 [ 0.22582784  0.0308808  -0.01150591]
 [ 0.22384496  0.12388784 -0.76796997]]
211 0.601581 [[-1.80547714 -0.77405614 -0.53468353]
 [ 0.2260406   0.03118362 -0.012021

326 0.536039 [[-2.24908972 -0.72137588 -0.14375244]
 [ 0.23777477  0.05721698 -0.04978871]
 [ 0.38550821  0.09518937 -0.90093428]]
327 0.535581 [[-2.25258994 -0.72085518 -0.14077294]
 [ 0.2378089   0.05738833 -0.0499942 ]
 [ 0.38681924  0.09495214 -0.90200812]]
328 0.535125 [[-2.25608516 -0.72033381 -0.13779901]
 [ 0.23784234  0.05755902 -0.05019834]
 [ 0.38812891  0.09471508 -0.9030807 ]]
329 0.53467 [[-2.25957561 -0.71981186 -0.13483062]
 [ 0.23787512  0.05772903 -0.05040113]
 [ 0.3894372   0.09447817 -0.9041521 ]]
330 0.534216 [[-2.26306105 -0.71928924 -0.13186775]
 [ 0.23790722  0.05789836 -0.05060257]
 [ 0.39074412  0.09424142 -0.90522224]]
331 0.533764 [[-2.26654172 -0.71876603 -0.12891036]
 [ 0.23793867  0.05806702 -0.05080268]
 [ 0.39204967  0.09400482 -0.90629119]]
332 0.533314 [[-2.27001739 -0.71824223 -0.12595841]
 [ 0.23796947  0.058235   -0.05100147]
 [ 0.39335385  0.09376835 -0.90735894]]
333 0.532864 [[-2.27348828 -0.71771783 -0.12301188]
 [ 0.23799963  0.05840232 -0.051

445 0.489523 [[-2.63596821 -0.65682817  0.17857781]
 [ 0.23868793  0.07379837 -0.06728305]
 [ 0.5324437   0.06806979 -1.02075005]]
446 0.489187 [[-2.63900089 -0.65627658  0.18105879]
 [ 0.23867886  0.07391191 -0.06738751]
 [ 0.53360611  0.06785184 -1.02169454]]
447 0.488851 [[-2.64203024 -0.655725    0.18353663]
 [ 0.23866957  0.07402516 -0.06749147]
 [ 0.53476733  0.06763412 -1.02263808]]
448 0.488517 [[-2.64505649 -0.65517342  0.18601133]
 [ 0.23866017  0.07413803 -0.06759493]
 [ 0.53592747  0.06741654 -1.02358067]]
449 0.488183 [[-2.64807963 -0.6546219   0.1884829 ]
 [ 0.23865059  0.07425059 -0.06769791]
 [ 0.53708649  0.06719916 -1.0245223 ]]
450 0.48785 [[-2.65109968 -0.65407038  0.19095135]
 [ 0.23864087  0.0743628  -0.0678004 ]
 [ 0.53824443  0.06698194 -1.02546299]]
451 0.487517 [[-2.65411663 -0.65351892  0.1934167 ]
 [ 0.238631    0.07447469 -0.06790242]
 [ 0.53940123  0.06676491 -1.02640271]]
452 0.487186 [[-2.65713024 -0.65296745  0.19587897]
 [ 0.23862098  0.07458623 -0.068

558 0.455603 [[-2.96050835 -0.59520572  0.44149387]
 [ 0.23701756  0.08481245 -0.07662673]
 [ 0.65717918  0.0445828  -1.12199783]]
559 0.455335 [[-2.96323204 -0.59467119  0.44368294]
 [ 0.2369995   0.08489607 -0.07669229]
 [ 0.6582275   0.04438535 -1.12284875]]
560 0.455067 [[-2.96595335 -0.59413689  0.44586989]
 [ 0.23698141  0.0849795  -0.07675763]
 [ 0.65927494  0.04418811 -1.12369895]]
561 0.454799 [[-2.96867228 -0.59360284  0.44805473]
 [ 0.23696327  0.08506271 -0.07682273]
 [ 0.66032141  0.04399103 -1.12454844]]
562 0.454532 [[-2.97138882 -0.59306908  0.45023745]
 [ 0.23694512  0.08514571 -0.07688759]
 [ 0.661367    0.04379413 -1.12539721]]
563 0.454266 [[-2.97410297 -0.59253556  0.45241809]
 [ 0.23692694  0.08522853 -0.07695223]
 [ 0.66241169  0.04359743 -1.12624514]]
564 0.454 [[-2.97681475 -0.59200227  0.45459661]
 [ 0.23690875  0.08531115 -0.07701667]
 [ 0.66345549  0.04340094 -1.12709248]]
565 0.453734 [[-2.97952414 -0.59146929  0.45677304]
 [ 0.23689054  0.08539356 -0.07708

669 0.428424 [[-3.24939179 -0.53761303  0.67278451]
 [ 0.23496045  0.09300012 -0.08275734]
 [ 0.76834619  0.02378632 -1.21236801]]
670 0.428201 [[-3.25187993 -0.53711164  0.67477119]
 [ 0.23494217  0.09306508 -0.08280402]
 [ 0.76930302  0.0236091  -1.21314764]]
671 0.427978 [[-3.25436616 -0.5366106   0.67675632]
 [ 0.23492391  0.09312992 -0.0828506 ]
 [ 0.77025908  0.02343206 -1.21392667]]
672 0.427756 [[-3.25685048 -0.53610986  0.67873985]
 [ 0.23490569  0.09319459 -0.08289704]
 [ 0.77121443  0.02325518 -1.21470511]]
673 0.427533 [[-3.2593329  -0.53560948  0.68072182]
 [ 0.23488745  0.09325915 -0.08294337]
 [ 0.77216899  0.0230785  -1.21548307]]
674 0.427311 [[-3.2618134  -0.53510946  0.68270224]
 [ 0.23486926  0.09332354 -0.08298957]
 [ 0.77312285  0.02290197 -1.21626043]]
675 0.42709 [[-3.264292   -0.53460974  0.68468112]
 [ 0.23485102  0.09338784 -0.08303566]
 [ 0.77407593  0.02272566 -1.2170372 ]]
676 0.426868 [[-3.26676869 -0.53411037  0.68665844]
 [ 0.23483285  0.09345197 -0.083

788 0.404037 [[-3.53298736 -0.48034769  0.89911413]
 [ 0.23291647  0.0998741  -0.08758705]
 [ 0.87728637  0.00391675 -1.30143845]]
789 0.403849 [[-3.53527069 -0.47988731  0.90093708]
 [ 0.2329006   0.09992536 -0.08762244]
 [ 0.87816238  0.00375991 -1.30215764]]
790 0.403661 [[-3.53755236 -0.47942728  0.90275884]
 [ 0.23288476  0.09997655 -0.08765776]
 [ 0.8790378   0.00360326 -1.30287635]]
791 0.403474 [[ -3.53983259e+00  -4.78967607e-01   9.04579341e-01]
 [  2.32868955e-01   1.00027591e-01  -8.76929909e-02]
 [  8.79912555e-01   3.44671146e-03  -1.30359459e+00]]
792 0.403287 [[ -3.54211116e+00  -4.78508264e-01   9.06398654e-01]
 [  2.32853144e-01   1.00078575e-01  -8.77281651e-02]
 [  8.80786717e-01   3.29037500e-03  -1.30431235e+00]]
793 0.4031 [[ -3.54438829e+00  -4.78049278e-01   9.08216774e-01]
 [  2.32837379e-01   1.00129448e-01  -8.77632722e-02]
 [  8.81660283e-01   3.13418917e-03  -1.30502975e+00]]
794 0.402913 [[ -3.54666376e+00  -4.77590650e-01   9.10033703e-01]
 [  2.32821614

910 0.382814 [[-3.80072498 -0.42673799  1.11324334]
 [ 0.23115876  0.1054863  -0.09144119]
 [ 0.97987878 -0.01405234 -1.38606155]]
911 0.382653 [[-3.80283451 -0.4263196   1.11493456]
 [ 0.23114581  0.10552748 -0.09146941]
 [ 0.98068613 -0.01419029 -1.38673091]]
912 0.382492 [[-3.80494285 -0.42590153  1.11662483]
 [ 0.23113289  0.1055686  -0.09149761]
 [ 0.981493   -0.01432806 -1.38740003]]
913 0.382332 [[-3.80704975 -0.42548379  1.11831415]
 [ 0.23111999  0.10560965 -0.09152575]
 [ 0.98229933 -0.0144657  -1.38806868]]
914 0.382172 [[-3.80915546 -0.42506638  1.12000251]
 [ 0.2311071   0.10565064 -0.09155385]
 [ 0.98310512 -0.01460317 -1.38873696]]
915 0.382011 [[-3.81125998 -0.42464933  1.1216898 ]
 [ 0.23109429  0.10569152 -0.09158193]
 [ 0.98391044 -0.01474052 -1.38940501]]
916 0.381851 [[-3.81336308 -0.4242326   1.12337613]
 [ 0.23108147  0.10573236 -0.09160993]
 [ 0.98471528 -0.01487772 -1.39007258]]
917 0.381692 [[-3.81546497 -0.4238162   1.12506151]
 [ 0.23106866  0.10577314 -0.09

1033 0.36437 [[-4.05096149 -0.37772989  1.31447232]
 [ 0.2297316   0.11006776 -0.09459524]
 [ 1.07554579 -0.02996432 -1.46581578]]
1034 0.364231 [[-4.05292368 -0.37735119  1.31605577]
 [ 0.22972128  0.11010136 -0.09461849]
 [ 1.07629514 -0.03008533 -1.46644413]]
1035 0.364091 [[-4.05488491 -0.37697282  1.3176384 ]
 [ 0.229711    0.11013488 -0.09464172]
 [ 1.07704413 -0.03020624 -1.46707213]]
1036 0.363952 [[-4.05684471 -0.37659475  1.31922019]
 [ 0.2297007   0.1101684  -0.09466494]
 [ 1.07779264 -0.03032696 -1.46769989]]
1037 0.363812 [[-4.05880356 -0.37621701  1.32080126]
 [ 0.22969043  0.11020183 -0.0946881 ]
 [ 1.07854068 -0.0304476  -1.46832728]]
1038 0.363673 [[-4.06076145 -0.37583956  1.3223815 ]
 [ 0.2296802   0.11023518 -0.09471123]
 [ 1.07928836 -0.03056812 -1.46895444]]
1039 0.363534 [[-4.06271791 -0.37546241  1.32396102]
 [ 0.22966997  0.1102685  -0.09473433]
 [ 1.08003557 -0.0306885  -1.46958125]]
1040 0.363396 [[-4.06467342 -0.37508556  1.32553971]
 [ 0.22965977  0.1103018

1154 0.348495 [[-4.28074789 -0.33408564  1.5006119 ]
 [ 0.22861567  0.11377265 -0.09718397]
 [ 1.16323745 -0.0437085  -1.53976309]]
1155 0.348372 [[-4.2825861  -0.33374265  1.5021069 ]
 [ 0.22860749  0.1138005  -0.09720361]
 [ 1.1639384  -0.04381483 -1.54035771]]
1156 0.348249 [[-4.28442335 -0.33339995  1.50360131]
 [ 0.22859932  0.11382826 -0.09722322]
 [ 1.164639   -0.04392108 -1.54095209]]
1157 0.348126 [[-4.28625965 -0.33305752  1.50509501]
 [ 0.22859116  0.11385603 -0.0972428 ]
 [ 1.16533923 -0.04402718 -1.54154623]]
1158 0.348003 [[-4.288095   -0.33271536  1.50658798]
 [ 0.22858299  0.11388373 -0.09726233]
 [ 1.16603911 -0.0441332  -1.54214001]]
1159 0.34788 [[-4.28992939 -0.3323735   1.50808036]
 [ 0.22857487  0.11391137 -0.09728184]
 [ 1.16673863 -0.04423911 -1.54273355]]
1160 0.347758 [[-4.29176283 -0.33203191  1.50957203]
 [ 0.22856672  0.11393902 -0.09730134]
 [ 1.16743767 -0.04434485 -1.54332685]]
1161 0.347636 [[-4.29359531 -0.33169061  1.51106298]
 [ 0.22855866  0.1139665

1263 0.335749 [[-4.4757185  -0.29830047  1.65979517]
 [ 0.22780806  0.11657345 -0.09917672]
 [ 1.23755479 -0.05465644 -1.60313332]]
1264 0.335638 [[-4.47745895 -0.29798666  1.66122186]
 [ 0.22780138  0.11659712 -0.09919372]
 [ 1.23821795 -0.05475107 -1.60370183]]
1265 0.335527 [[-4.47919846 -0.29767311  1.66264796]
 [ 0.22779472  0.11662077 -0.0992107 ]
 [ 1.23888075 -0.0548456  -1.6042701 ]]
1266 0.335416 [[-4.48093748 -0.29735979  1.66407347]
 [ 0.22778808  0.11664437 -0.09922766]
 [ 1.23954332 -0.05494004 -1.60483813]]
1267 0.335306 [[-4.48267555 -0.29704675  1.66549838]
 [ 0.22778146  0.11666793 -0.0992446 ]
 [ 1.24020553 -0.05503438 -1.60540605]]
1268 0.335195 [[-4.48441267 -0.29673395  1.66692281]
 [ 0.22777484  0.11669146 -0.09926151]
 [ 1.24086738 -0.05512862 -1.60597372]]
1269 0.335084 [[-4.48614883 -0.29642141  1.66834664]
 [ 0.22776823  0.11671494 -0.09927838]
 [ 1.24152887 -0.05522276 -1.60654116]]
1270 0.334974 [[-4.48788452 -0.29610911  1.66976988]
 [ 0.22776163  0.116738

1374 0.324019 [[-4.66398954 -0.26497394  1.8147409 ]
 [ 0.22713938  0.11900209 -0.10093644]
 [ 1.30926692 -0.06456616 -1.66493642]]
1375 0.323919 [[-4.66564226 -0.26468706  1.8161068 ]
 [ 0.22713399  0.11902224 -0.10095119]
 [ 1.30989635 -0.06465019 -1.66548181]]
1376 0.323818 [[-4.66729403 -0.26440042  1.8174721 ]
 [ 0.22712857  0.11904241 -0.10096594]
 [ 1.31052542 -0.06473411 -1.66602695]]
1377 0.323718 [[-4.66894531 -0.26411402  1.81883693]
 [ 0.22712314  0.11906255 -0.10098065]
 [ 1.31115425 -0.06481793 -1.66657186]]
1378 0.323618 [[-4.67059565 -0.26382786  1.82020128]
 [ 0.22711775  0.11908263 -0.10099534]
 [ 1.31178272 -0.06490169 -1.66711664]]
1379 0.323517 [[-4.6722455  -0.26354191  1.82156503]
 [ 0.22711234  0.11910271 -0.10101001]
 [ 1.31241095 -0.06498533 -1.66766119]]
1380 0.323417 [[-4.67389441 -0.26325619  1.82292831]
 [ 0.22710697  0.11912271 -0.10102464]
 [ 1.31303895 -0.06506893 -1.6682055 ]]
1381 0.323317 [[-4.67554283 -0.26297069  1.82429111]
 [ 0.22710156  0.119142

1492 0.312711 [[-4.85406971 -0.23266147  1.97250938]
 [ 0.22656333  0.12119787 -0.10255585]
 [ 1.38163912 -0.07388155 -1.72799325]]
1493 0.31262 [[-4.85563946 -0.23240043  1.9738183 ]
 [ 0.22655898  0.12121496 -0.10256858]
 [ 1.38223684 -0.07395556 -1.72851694]]
1494 0.312528 [[-4.85720873 -0.23213959  1.97512674]
 [ 0.22655457  0.12123209 -0.1025813 ]
 [ 1.3828342  -0.07402943 -1.7290405 ]]
1495 0.312437 [[-4.85877752 -0.23187897  1.97643471]
 [ 0.22655024  0.12124911 -0.10259399]
 [ 1.38343143 -0.0741033  -1.72956383]]
1496 0.312346 [[-4.86034536 -0.23161854  1.97774231]
 [ 0.22654587  0.12126616 -0.10260667]
 [ 1.38402832 -0.07417704 -1.73008704]]
1497 0.312255 [[-4.86191273 -0.23135832  1.97904944]
 [ 0.22654152  0.12128318 -0.10261934]
 [ 1.38462496 -0.07425072 -1.73061001]]
1498 0.312164 [[-4.86347961 -0.23109831  1.9803561 ]
 [ 0.2265372   0.12130016 -0.10263199]
 [ 1.38522136 -0.07432433 -1.73113286]]
1499 0.312073 [[-4.86504555 -0.23083852  1.98166227]
 [ 0.22653291  0.1213170

### Learning rate가 너무 클때

In [9]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3])) #tf.random_normal([입력값수, 출력값수])
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

#Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [10]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], 
                                      feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    # close test    
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_data}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_data, Y: y_data}))
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 7.33347 [[ 1.24662495  0.02356297 -0.06824023]
 [ 1.5329963   0.13232106 -0.40997544]
 [-0.10890124 -0.5869568   0.43812039]]
1 22.0015 [[ 0.12352046  0.58536351  0.49306369]
 [-2.58797741  2.75580883  1.0875113 ]
 [-4.22734308  2.22436595  1.7452395 ]]
2 27.9677 [[ 0.49852046 -0.35091823  1.05434537]
 [-0.15047741 -1.17910051  2.58492041]
 [-1.78984308 -1.52362776  3.0557332 ]]
3 9.36049 [[ 0.87351155  0.21158154  0.11685449]
 [ 2.28700471  1.44589913 -2.47756147]
 [ 0.64764798  1.28887188 -2.1942575 ]]
4 25.8795 [[-0.05690125  0.57949448  0.67935443]
 [-1.24823904  3.481143   -0.97756159]
 [-2.59765387  3.2216742  -0.8817575 ]]
5 4.95976 [[ 0.31809872 -0.35800534  1.24185431]
 [ 1.18926096 -0.45635664  0.52243817]
 [-0.16015387 -0.52832544  0.43074232]]
6 15.1401 [[-0.05597942  0.20373765  1.05418944]
 [ 0.03296083  2.16701865 -0.94463682]
 [-0.92265522  2.28314686 -1.61822867]]
7 16.9538 [[ 0.31894508 -0.7336756   1.61667824]
 [ 2.4703095  -1.77030754  0.55534077]
 [ 1.51476896 -1

Overshooting이 되어버림

### Learning rate가 너무 작을때

In [11]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3])) #tf.random_normal([입력값수, 출력값수])
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

#Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [12]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], 
                                      feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    # close test    
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_data}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_data, Y: y_data}))
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
1 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
2 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
3 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
4 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
5 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
6 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
7 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0

108 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
109 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
110 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
111 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
112 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
113 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
114 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]
 [-0.39983943  0.277024    0.55403823]]
115 4.38157 [[-0.99163026 -1.00799954  0.38226086]
 [-0.53700167 -0.95994359 -0.29832083]


Local minimum에 갇혀버림