## Tensor Manipulation (텐서 다루기)

In [5]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

### Simple ID array and slicing

In [6]:
t = np.array([0., 1., 2., 3., 4., 5., 6])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


### 2D Array

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


### Shape, Rank, Axis

In [10]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()

array([4])

In [13]:
t = tf.constant([[1, 2], [3, 4]])
tf.shape(t).eval()

array([2, 2])

axis는 가장 바깥의 각괄호의 경우 axis=0이고 숫자가 들어있는 가장 안의 각괄호가 axis=3인 경우이다.

In [14]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

### Matmul VS multiply

In [15]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval() # 행렬 곱이 나옴

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

In [16]:
(matrix1*matrix2).eval() # 각 행과의 곱이 나옴

array([[ 1.,  2.],
       [ 6.,  8.]], dtype=float32)

In [17]:
# Operations between the same shapes
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

### Broadcasting

#### matrix1과 matrix2의 shape를 자동으로 맞춰줌

In [18]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1 + matrix2).eval()

array([[ 4.,  5.]], dtype=float32)

In [20]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1 + matrix2).eval()

array([[ 4.,  6.]], dtype=float32)

In [19]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1 + matrix2).eval()

array([[ 4.,  5.],
       [ 5.,  6.]], dtype=float32)

### Reduce mean

평균을 구하는 function

In [21]:
tf.reduce_mean([1, 2], axis=0).eval() # 정수형의 경우 정수의 결과만 도출

1

In [22]:
x = [[1., 2.],
     [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [23]:
tf.reduce_mean(x, axis=0).eval() # 세로 축

array([ 2.,  3.], dtype=float32)

In [24]:
tf.reduce_mean(x, axis=1).eval() # 가로 축

array([ 1.5,  3.5], dtype=float32)

In [25]:
tf.reduce_mean(x, axis=-1).eval() # 가로 축

array([ 1.5,  3.5], dtype=float32)

### Reduce sum

합을 구하는 function

In [26]:
tf.reduce_sum(x).eval()

10.0

In [29]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [30]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [28]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

### Argmax