## Tensor Manipulation (텐서 다루기)

In [1]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

### Simple ID array and slicing

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


### 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


### Shape, Rank, Axis

In [4]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()

array([4])

In [5]:
t = tf.constant([[1, 2], [3, 4]])
tf.shape(t).eval()

array([2, 2])

axis는 가장 바깥의 각괄호의 경우 axis=0이고 숫자가 들어있는 가장 안의 각괄호가 axis=3인 경우이다.

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

### Matmul VS multiply

In [7]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval() # 행렬 곱이 나옴

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

In [8]:
(matrix1*matrix2).eval() # 각 행과의 곱이 나옴

array([[ 1.,  2.],
       [ 6.,  8.]], dtype=float32)

In [9]:
# Operations between the same shapes
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

### Broadcasting

#### matrix1과 matrix2의 shape를 자동으로 맞춰줌

In [10]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1 + matrix2).eval()

array([[ 4.,  5.]], dtype=float32)

In [11]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1 + matrix2).eval()

array([[ 4.,  6.]], dtype=float32)

In [12]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1 + matrix2).eval()

array([[ 4.,  5.],
       [ 5.,  6.]], dtype=float32)

### Reduce mean

평균을 구하는 function

In [13]:
tf.reduce_mean([1, 2], axis=0).eval() # 정수형의 경우 정수의 결과만 도출

1

In [14]:
x = [[1., 2.],
     [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [15]:
tf.reduce_mean(x, axis=0).eval() # 세로 축

array([ 2.,  3.], dtype=float32)

In [16]:
tf.reduce_mean(x, axis=1).eval() # 가로 축

array([ 1.5,  3.5], dtype=float32)

In [17]:
tf.reduce_mean(x, axis=-1).eval() # 가로 축

array([ 1.5,  3.5], dtype=float32)

### Reduce sum

합을 구하는 function

In [18]:
tf.reduce_sum(x).eval()

10.0

In [19]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [20]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [21]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

### Argmax

가장 큰 값이 나온 원소의 인덱스를 출력하는 function

axis=0의 경우는 세로, axis=-1이나 1의 경우는 가로를 축으로 두고 출력한다

In [23]:
x = [[0, 1, 2], 
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [24]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [25]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

### Reshape

tensor의 shape를 바꾸는 function

In [26]:
t = np.array([[[0, 1, 2], 
              [3, 4, 5]],
             
             [[6, 7, 8],
             [9, 10, 11]]])
t.shape

(2, 2, 3)

In [27]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### Reshape(squeeze, expand)

squeeze 함수는 n차원의 하나로 분리된 여러 원소들을 한단계 낮은 차원으로 압축함

expand 함수는 n차원의 여러 원소들을 한단계 높은 차원으로 확장함

In [36]:
tf.squeeze([[0], [1], [2], [3]]).eval()

array([0, 1, 2, 3])

In [42]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

### One hot

one-hot 형식으로 변환해주는 function

In [43]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [44]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

### Casting

In [45]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [46]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

### Stack

In [47]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

### Ones and Zeros like

x와 같은 모양을 하는 tensor를 0 또는 1로 채워서 만들어 줌

In [50]:
x = [[0, 1, 2],
    [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

### Zip

In [52]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [53]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
