In [1]:
import tensorflow as tf

### 여러개의 feature를 가지는 Linear regresssion

다음의 경우 데이터가 많아지면 사용하지 않음

In [5]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1], name='weight1'))
w2 = tf.Variable(tf.random_normal([1], name='weight2'))
w3 = tf.Variable(tf.random_normal([1], name='weight3'))
b = tf.Variable(tf.random_normal([1], name='bias'))

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  12803.1 
Prediction:
 [ 56.05493546  61.04105759  63.69265366  64.21528625  49.53528976]
10 Cost:  8.66093 
Prediction:
 [ 156.1078949   181.31352234  182.19064331  193.25852966  141.27531433]
20 Cost:  8.51776 
Prediction:
 [ 156.40200806  181.68322754  182.54640198  193.64794922  141.5597229 ]
30 Cost:  8.49193 
Prediction:
 [ 156.39431763  181.69013977  182.54473877  193.64807129  141.56738281]
40 Cost:  8.46609 
Prediction:
 [ 156.38569641  181.69593811  182.54194641  193.64701843  141.57420349]
50 Cost:  8.44048 
Prediction:
 [ 156.37712097  181.70173645  182.53921509  193.64596558  141.58099365]
60 Cost:  8.41499 
Prediction:
 [ 156.36857605  181.70750427  182.53648376  193.64494324  141.58776855]
70 Cost:  8.38968 
Prediction:
 [ 156.36004639  181.71324158  182.5337677   193.64389038  141.5945282 ]
80 Cost:  8.36438 
Prediction:
 [ 156.35151672  181.71899414  182.53103638  193.64286804  141.60125732]
90 Cost:  8.33926 
Prediction:
 [ 156.34301758  181.72470093  182.5282

### Matrix

x_data의 경우 성적 데이터, y_data의 경우 총합의 데이터

In [8]:
x_data = [[73., 80., 75.], [93., 88., 93.], 
          [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X, Y는 placeholder이고 shape는 placeholder에 들어갈 자료형의 차원이나 형태를 입력한다

In [9]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  10553.9 
Prediction:
 [[ 251.21713257]
 [ 287.8678894 ]
 [ 290.87545776]
 [ 316.48727417]
 [ 216.38613892]]
10 Cost:  42.0743 
Prediction:
 [[ 160.49533081]
 [ 178.87416077]
 [ 183.45761108]
 [ 199.51437378]
 [ 133.26106262]]
20 Cost:  41.754 
Prediction:
 [[ 160.19604492]
 [ 178.56141663]
 [ 183.12503052]
 [ 199.15466309]
 [ 133.03218079]]
30 Cost:  41.5312 
Prediction:
 [[ 160.17037964]
 [ 178.57745361]
 [ 183.1164856 ]
 [ 199.14782715]
 [ 133.05403137]]
40 Cost:  41.3096 
Prediction:
 [[ 160.14564514]
 [ 178.59443665]
 [ 183.1089325 ]
 [ 199.14205933]
 [ 133.07659912]]
50 Cost:  41.0891 
Prediction:
 [[ 160.12097168]
 [ 178.61138916]
 [ 183.10142517]
 [ 199.13630676]
 [ 133.09910583]]
60 Cost:  40.8698 
Prediction:
 [[ 160.09637451]
 [ 178.62832642]
 [ 183.09394836]
 [ 199.13058472]
 [ 133.12156677]]
70 Cost:  40.6519 
Prediction:
 [[ 160.07182312]
 [ 178.64515686]
 [ 183.08644104]
 [ 199.12484741]
 [ 133.1439209 ]]
80 Cost:  40.4349 
Prediction:
 [[ 160.04733276]
 [ 178.66